//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVoucher.Lib.Models.EVoucher
{
    using System;
    using System.Collections.Generic;
    
    public partial class BridgeStone_Register
    {
        public int Id { get; set; }
        public string Fullname { get; set; }
        public string Phone { get; set; }
        public string Manufacturer { get; set; }
        public string Automaker { get; set; }
        public string CarModel { get; set; }
        public string License { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Code { get; set; }
        public string SendCodeStatus { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> SendCodeDate { get; set; }
    }
}
