//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVoucher.Lib.Models.EVoucher
{
    using System;
    using System.Collections.Generic;
    
    public partial class BridgeStone_ClaimProduct
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public System.DateTime ClaimedDate { get; set; }
        public string CreatedBy { get; set; }
        public int Status { get; set; }
        public string CodeVoucher { get; set; }
    }
}
