// <auto-generated />
namespace Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class initial_acc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_acc));
        
        string IMigrationMetadata.Id
        {
            get { return "201803310552577_initial_acc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
